"""Create analyses and feedbacks tables

Revision ID: 7f447e815b92
Revises: 
Create Date: 2026-03-31 19:43:11.185077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f447e815b92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('input_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('classification_data', sa.JSON(), nullable=True),
    sa.Column('sentiment_data', sa.JSON(), nullable=True),
    sa.Column('credibility_data', sa.JSON(), nullable=True),
    sa.Column('fact_check_data', sa.JSON(), nullable=True),
    sa.Column('article_info', sa.JSON(), nullable=True),
    sa.Column('analyzed_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('user_verdict', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_analysis_id'), 'feedbacks', ['analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_analysis_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
